### ISSUE TITLE
Is velocity information ignored?

### ISSUE THREAD

**Issue by dosas** [josephernest/SamplerBox#65]
I am sending midi messages with different velocity information to the SamplerBox but the volume is always the same.

Looking at [this](https://github.com/josephernest/SamplerBox/blob/master/samplerbox.py#L112) initialized but unused var `self.velocity`: Is the velocity information ignored or is this a bug?

**Comment by josephernest** [comment]
Hi, 
Velocity information in the MIDI message is used to launch different samples (see for example the Salamander piano sample set's `definition.txt`) rather than modulating the volume, so this is not a bug.

https://github.com/josephernest/SamplerBox/blob/master/samplerbox.py#L110 to L112 is for keeping all variables from init in the object itself, no matter if it is used or not - it may be useful later.
